### ISSUE TITLE
is:issue is:open  Want to Place the Starting Point at the Top

### ISSUE THREAD

**Issue by e-yokotsuka** [mzusin/react-round-slider#1]
Hello,

I'm really enjoying using this component—it's both useful and looks great.
However, I'd like to know how to place the starting point at the top. 
Could you guide me on how to do that?

Thank you.

**Comment by mzusin** [comment]
Hello,
You can use **pathStartAngle** and **pathEndAngle** properties:

```js
<RoundSlider
   pathStartAngle={ 270 }
   pathEndAngle={ 269.999 }
/>
```

The documentation about these properties is [here](https://react-round-slider.mzsoft.org/pages/path-settings.html).

**Comment by e-yokotsuka** [comment]
Thank you very much!!

I overlooked the documentation.

https://react-round-slider.mzsoft.org/pages/basic-usage.html#:~:text=To%20place%20the%20starting%20point%20at%20the%20top
