### ISSUE TITLE
Missing values

### ISSUE THREAD

**Issue by mertavcioglu** [mzusin/react-round-slider#3]
Circle does not take some values.

I realize that it does not take values multiplfy of 0.4 (0.4, 0.8, 1.2, 1.6 etc.)

When I remove 

```
 pathStartAngle={90}
 pathEndAngle={360}
```
everything works good but I need a start angle of 90 and end of 360.

```
<RoundSlider
      min={0}
      max={3}
      step={0.1}
      arrowStep={0.1}
      round={1}
      enableTicks={true}
      ticksCount={30}
      ticksColor="#80BA26"
      pathStartAngle={90}
      pathEndAngle={360}
      pathRadius={125}
      hideText={true}
      showTickValues={false}
      ticksWidth={3}
      ticksHeight={13}
      pathBgColor={"#e2e2e2"}
      pointerBgColor={"#80BA26"}
      pointerBgColorSelected={"#80BA26"}
      animateOnClick={true}
      animationDuration={500}
      onChange={(value) => setController1value(value[0].value)}
/>
```

EDIT: 

https://react-round-slider.mzsoft.org/pages/ticks-settings.html

In this example, it does not take some values too!

![image](https://github.com/mzusin/react-round-slider/assets/34686131/c3a54be7-ad1f-4ba9-8434-d26af9e57702)

![image](https://github.com/mzusin/react-round-slider/assets/34686131/8915d088-b22c-4fc6-9781-ef6518f7892a)

**Comment by mzusin** [comment]
The issue should be fixed in the latest version (1.0.2).
